### PR TITLE
Achievements pdf export

### PR DESCRIPTION
**Pull request by paulbert**
Note the showdown package is a dependency for the markdown viewer so it shouldn't add too much overall to the app.

Still a work in progress

### CODE REVIEW

**Comment by singharpita** [comment]
@paulbert made PDF based on HTML element. Regarding styling found that using html2canvas could just print pdf as its being displayed. Shall i try that approach to see how it will look?

**Comment by paulbert** [comment]
@singharpita I tried html2canvas and had trouble getting it working. Also, because the HTML is converted to vector there is no way to copy from the outputted PDF, which I do not think is ideal.

Sans serif is a family of fonts rather than a specific font. `Times` is a serif font.  It's likely `Arial` or `Helvetica` are available sans serif options. See http://web.mit.edu/jmorzins/www/fonts.html for a list of a few more possible sans serif fonts

**Comment by paulbert** [comment]
Trying to pull this back in as a solution for health/surveys, but there are errors with the build

**Comment by paulbert** [comment]
Closing since we are using a different javascript to PDF library

**Pull request closed without merging**
