### PR TITLE
[#633] snackbar behaviour reworked(connects #633)

### PR DESCRIPTION
**Pull request by BasnetSamriddhi**
In this PR I have changed the duration of alert snackbar which needed manual removal and the color of the respected snacbars

### CODE REVIEW

**Comment by BasnetSamriddhi** [comment]
I have just worked using just one change, if approved I will be making changes to other files as well.

**Comment by lmmrssa** [comment]
I see the changes addresses issue upto some extend. But the main problem here is that after certain action is taken like move to next page or when next snackbar shows up, old snackbar needs to be gone. Snackbar staying there when page or context is not relevant is the main issue. @Tille88 is that correct?

**Comment by BasnetSamriddhi** [comment]
@paulbert I have tried on removing the snackbar from appearing on new page. Could you please have a look at it and I have implemented this only in course section only

**Comment by Tille88** [comment]
@lmmrssa @BasnetSamriddhi 
Yes, I meant something like that. It is a deeper question exactly what kind of behavior (and later on styling) that would be good for different messages. 
Having it react to a change of route would also be behavior that would be okay - the main thing was that it was weird to have it stick around for ten minutes unless closed manually. 
Making sure it gets replaced by any new snackbar would of course be required, anything else would be confusing I think...

Good first iteration. An improvement in my view, but exact behaviour I think is something that maybe you should wait for a few people's opinion. I think both could work for this particular event.

**Comment by paulbert** [comment]
I'm going to close this.  It basically makes the two methods equivalent.  Instead of changing `showAlert` we should be using it consistently for errors or unexpected behavior only.

**Pull request closed without merging**
