### PR TITLE
Update input validation (fixes #6284)

### LINKED ISSUE #6284: myHealth: allowing 0 in Vitals fields
since we are restricting number to be greater or equal to 0, it doesn't make sense to have value 0 in weight, height, pulse and pressure in it.

Screenshot_2020-05-12 Planet Learning(2)

### PR DESCRIPTION
**Pull request by jsschf**
Issue #6284 

Added validation to prevent temperature, blood pressure, height and weight from being 0.

Annotation 2020-05-13 002510

### CODE REVIEW

**Comment by jsschf** [comment]
I'm unsure if it would make more sense to just replace the custom validator _positiveNumberValidator_ with the built in validator, so I kept both in.

**Comment by jsschf** [comment]
@paulbert Will do! Do you want me to remove _postiveNumberValidator_ from _custom-validators.ts_ as well? I think that _health-event.component.ts_ was the only place it was used.

**Comment by paulbert** [comment]
@jsschf It's used in a few other forms, so you can leave it.  Thanks!

**Comment by jsschf** [comment]
@paulbert Is there anything else I need to do with this PR?

**Pull request merged**
