### PR TITLE
Upgrade to Angular 7 (fixes #2010)

### LINKED ISSUE #2010: Update to latest Angular & RxJS
As part of update will also have to deal with this error:
```
ERROR in src/app/shared/user.service.ts(73,17): error TS2345: Argument of type '(userData: any) => Observable<[any, any]> | Observable<{}[]>' is not assignable to parameter of type '(value: any, index: number) => ObservableInput<[any, any]>'.
  Type 'Observable<[any, any]> | Observable<{}[]>' is not assignable to type 'ObservableInput<[any, any]>'.
    Type 'Observable<{}[]>' is not assignable to type 'ObservableInput<[any, any]>'.
      Type 'Observable<{}[]>' is not assignable to type 'Iterable<[any, any]>'.
        Property '[Symbol.iterator]' is missing in type 'Observable<{}[]>'.
```

### PR DESCRIPTION
**Pull request by paulbert**
#2010

### CODE REVIEW

**Comment by lmmrssa** [comment]
@paulbert  On fresh installation, it gives **stderr** and never completes. Have to login to vagrant and run commands inside again to make it run.
screen shot 2018-11-15 at 07 20 02

**Comment by paulbert** [comment]
For me it just stalls at that part, but completes the script.  It might be slow because it has a bit to install from npm.

Problem is it doesn't do the npm install, version is still 6...
image

**Comment by paulbert** [comment]
It's throwing a bunch of errors like the below during the npm install.  Could it be an issue with the way we mount `node_modules`?

```
    dev: "stderr"
    dev: npm
    dev:  WARN rollback
    dev:  Rolling back fast-deep-equal@2.0.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/vagrant/node_modules/@angular-devkit/schematics/node_modules/fast-deep-equal/package.json.99337135'
    dev: npm
    dev:  WARN
    dev:  
    dev: rollback
    dev:  Rolling back @angular-devkit/schematics@7.0.6 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/vagrant/node_modules/@angular-devkit/schematics/package.json.543374851'
```

**Comment by paulbert** [comment]
@lmmrssa Fixed the issue with `vagrant up` and a few cosmetic issues from the upgrade.  I think it's ready for another test.

**Comment by lmmrssa** [comment]
Tested with clean installation and it had new angular package installed and application was running fine.

**Pull request merged**
