### PR TITLE
Added space - Issue#3950

### PR DESCRIPTION
**Pull request by samuelchen1213**
Screen Shot 2019-06-04 at 11 30 35 AM

### CODE REVIEW

**Comment by samuelchen1213** [comment]
Understood, I will fix this!

**Comment by samuelchen1213** [comment]
@paulbert @lmmrssa  Would it be more beneficial to create a complete different class in styles.scss just for `white-space:pre` or can I add it to the `ellipsis-title` class (Or would this interfere with styling with other components)

**Comment by paulbert** [comment]
@samuelchen1213 The only usage that might have an issue is in the CoursesStepViewComponent (click a course to open CoursesViewComponent and then click yellow "View Step" button), so I think adding it to `.ellipsis-title` would work.

**Comment by samuelchen1213** [comment]
@paulbert Perfect! I did not want to cause future issues. My pull request will be on its way in a minute!

**Pull request merged**
