### PR TITLE
added default team type(Fixed 4827)

### LINKED ISSUE #4827: Notification: Older teams show undefined
Older teams do not have a `type` property so notifications have `undefined` at the end of the message.  This should default to `'team'`

image

### PR DESCRIPTION
**Pull request by wanglihe2010**
fixed #4827

### CODE REVIEW

**Comment by wanglihe2010** [comment]
@paulbert  Is it okay to assign 'team' to team.type if team.type is undefined?

**Comment by paulbert** [comment]
> @paulbert Is it okay to assign 'team' to team.type if team.type is undefined?

No.  Objects in javascript are always references, so changing a property on `team` changes the original object.

Please create a new variable.

**Comment by wanglihe2010** [comment]
Hi, @paulbert , I added `teamType` variable, but I still have to change `team.type` to `teamType` 6 times

**Comment by paulbert** [comment]
> Hi, @paulbert , I added `teamType` variable, but I still have to change `team.type` to `teamType` 6 times

Yes, but now if we make a future change to the message we don't have to change it again 6 times!

**Comment by wanglihe2010** [comment]
> > Hi, @paulbert , I added `teamType` variable, but I still have to change `team.type` to `teamType` 6 times
> 
> Yes, but now if we make a future change to the message we don't have to change it again 6 times!

Thanks for clarification

**Pull request merged**
