### PR TITLE
[#1640] dashboard overlapping text (connects #1640)

### PR DESCRIPTION
**Pull request by singharpita**

### CODE REVIEW

**Comment by lmmrssa** [comment]
Looks good with the margin but found that whole tile gets affected by height of one item which is happening on master branch as well. So could you also fix it along with this PR.
sketch 79

**Comment by paulbert** [comment]
Added some spacing for readability and changed how the height is set to preserve the vertical centering of the text.

After looking at this, I think there isn't a pure CSS solution.  The text needs to be vertically centered when it doesn't overflow, but aligned to top when it does.

**Comment by lmmrssa** [comment]
Text is still overlapped by `remove` icon
screen shot 2018-07-31 at 14 45 55

**Comment by lmmrssa** [comment]
@dogi @paulbert changes made will add margin to top and center text based on remaining height. But it will still only show center part of the title. Couldn't find conditional styling that can be implemented based on content height.

**Comment by lmmrssa** [comment]
@paulbert reverted back the changes

**Comment by paulbert** [comment]
Closing.  This doesn't really improve upon the issue.

**Pull request closed without merging**
