### PR TITLE
Refactor dialogs forms (connects #1527)

### PR DESCRIPTION
**Pull request by paulbert**
Adds a function which takes a callback to DialogsFormService and implements on FeedbackDirective

### CODE REVIEW

**Comment by gcantieni** [comment]
Ugh, so ironically I was trying to clean this branch through rebasing and it added all of the commits from master from the past few days. Also, last time I tried to rebase this happened as--I'd appreciate if someone could tell me how to fix this so I don't make the mistake in the future.

**Comment by gcantieni** [comment]
Ok nvm I cleaned it up

**Comment by gcantieni** [comment]
Upon refactoring the ChangePasswordDirective, it has become apparent that when requesting to change the password it doesn't matter if you input the correct old password (the password required to update the user's password). In the console we get:
`ERROR >>>  Http post 14 request HttpErrorResponse {headers: HttpHeaders, status: 401, statusText: "Unauthorized", url: "http://localhost:2200/_session", ok: false, …}`
and yet the password is still updated successfully. I think this can be recreated in master... should I open it as a new issue or incorporate it as part of this refactoring--it might be as simple as a single check perhaps?

**Comment by paulbert** [comment]
Closing due to inactivity

**Pull request closed without merging**
