### PR TITLE
all: smoother submissions list

### LINKED ISSUE #7630: submissions: table responsiveness
Responsiveness options for the submissions table.

image

### PR DESCRIPTION
**Pull request by RheuX**
Fixes #7630 

### Horizontal Scroll Screen Option:
image
image

### CODE REVIEW

**Comment by Gavinp14** [comment]
I like this idea. We would have to figure out how to style it, so it looks neat and organized

**Comment by jessewashburn** [comment]
I think it's fine if people have to scroll a bit to see the very right hand side on narrow screens. Obviously, it's not ideal, but many pages on the site currently work that way, and it may not be the best use of time reinventing everything for the very few people who will be using a mobile browser.

**Comment by sahilvunnam** [comment]
I personally like the horizontal scroll screen option, I think it is cleaner compared to stacking each row formation. Perhaps we could decrease the margin between each column or decrease the width of each column so the user doesn't have to scroll so much horizontally.

**Comment by RheuX** [comment]
okay thansk for the feedback, ill stick with the horizontal scroll option then :)

**Review by Mutugiii — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
