### PR TITLE
feedback title truncation (connects #3936)

### PR DESCRIPTION
**Pull request by Liew211**
Screenshot_2019-06-17 Planet Learning

Truncated name, turned params into an object.  I'm not sure of the exact method of display, so I used JSON.stringify for a temporary fix, so please let me know what you'd like best for this.

### CODE REVIEW

**Comment by Liew211** [comment]
Screenshot_2019-06-18 Planet Learning
This is what the page looks like now.

**Comment by paulbert** [comment]
@Liew211 If there are parameters, it would be better to only show them after clicking a "Show Page Parameters" button

**Comment by Liew211** [comment]
Screenshot_2019-06-24 Planet Learning
Screenshot_2019-06-24 Planet Learning(1)
I partly copied the toggle functionality from the search filter in resources, let me know if you want the button to be above/below the details, and if the size of the button should be smaller.

**Comment by paulbert** [comment]
I think the button should be in the top blue toolbar after the edit button and maybe say "Show URL Details" or "Show Page Details"

Also I think the details should have a different background like with resources/courses so it stands out as different.

**Comment by Liew211** [comment]
@paulbert would a mat-card be ok for the details?  Also, should the button be aligned to the right, or just be next to the edit button?

**Comment by Liew211** [comment]
Screenshot_2019-06-28 Planet Learning
@paulbert how's this?

**Comment by paulbert** [comment]
@Liew211 I like what you have in that screenshot.  I think maybe add a line on top in bold that says **Page Parameters** as a heading and on the show/hide details button add `*planetAuthorizedRoles` to limit this to admins.  I think it would just be confusing for normal members.

**Comment by Liew211** [comment]
@paulbert made the changes, take a look!

**Pull request merged**
