### PR TITLE
re-ordering courses tool bar buttons fixes ( #4649 )

### PR DESCRIPTION
**Pull request by dogeTheCoder**
image

image

note this is the updated courses tool-bar, which is now symmetrical to the resource tool-bar. ^^^

### CODE REVIEW

**Comment by dogeTheCoder** [comment]
Changed the following component to match the Resources tool bar. Fixing issue 4649. =>https://github.com/open-learning-exchange/planet/issues/4649

**Comment by dogeTheCoder** [comment]
> Note that there were different conditions for each button being shown. By simply moving around the elements the conditions are now off.
> 
> Again I would suggest you start with writing issues and PRs for [open-learning-exchange.github.io](https://github.com/open-learning-exchange/open-learning-exchange.github.io) before creating PRs on this project.

I felt like the issues in that repository aren't as **juicy** as the ones in this one.

**Comment by paulbert** [comment]
@dogeTheCoder Thanks for fixing the indentation, but you did not address this part of the request:

> Note that there were different conditions for each button being shown. By simply moving around the elements the conditions are now off.

**Comment by paulbert** [comment]
@dogeTheCoder Please let me know if you need any more help or explanation on this PR.

I'll be closing this on Monday if there is not an update before then.

**Comment by dogeTheCoder** [comment]
> @dogeTheCoder Thanks for fixing the indentation, but you did not address this part of the request:
> 
> > Note that there were different conditions for each button being shown. By simply moving around the elements the conditions are now off.

Hey just went through the button tag, could you highlight what attributes need to be refactored? thanks @paulbert

**Comment by paulbert** [comment]
@dogeTheCoder Please look through the template and make sure the conditions before your changes match the conditions after for the two buttons changed.

**Comment by dogeTheCoder** [comment]
> @dogeTheCoder Please look through the template and make sure the conditions before your changes match the conditions after for the two buttons changed.

Just went through the tags and i couldn't find any broken conditions. Also i didn't find any broken css. @paulbert

**Comment by paulbert** [comment]
@dogeTheCoder The conditions are not broken, but how they are applied to the buttons has changed.  You need to make sure that the conditions that applied to each of the buttons before you made the changes are the same as the ones that apply to each of the buttons after the changes.

**Comment by paulbert** [comment]
@dogeTheCoder Do you need any more explanation with this PR?

I'll be closing this on Friday if there are no updates.

**Comment by paulbert** [comment]
Closing since there are no recent updates.

**Pull request closed without merging**
