### PR TITLE
Show version of parent & planet (connects #1671)

### PR DESCRIPTION
**Pull request by paulbert**
Uses the new `/version` endpoint rather than the database.

### CODE REVIEW

**Comment by paulbert** [comment]
I'd like to merge this so we at least don't have to manually add a configuration document to be able to login, but this doesn't fully fix the issue.

It's not working to show the version in the dashboard, and the GET request is failing to the nation and returning this error:
```
Failed to load https://paulbert.media.mit.edu/version: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 405.
```
Because the development environment won't have a local `/version` location, I can't debug why the local version isn't showing up in the docker container, either.  In any case I just wanted to fix up the changes we made to the configuration database and then pass this off.

**Comment by paulbert** [comment]
Figured out what was going wrong: the headers were incorrect for the request.  This appears to work now.

**Comment by paulbert** [comment]
After testing with the `dev` and `paulbert` nations, it looks like the changes I made were not enough and we will need to add the Access-Control-Allow-Origin header to the server.

@mappuji @dogi @lmmrssa Tagging so we can discuss at systems meeting.

**Comment by paulbert** [comment]
@mappuji We're not using the database anymore for the version number.  This PR removes changes that would involve `db-init` or CouchDB for storing & accessing the version.  Basically the DB would be easier to accidentally change, so with this we just expose a file to read externally with the version as text (see #1666 for that change).  Problem is we need to read that file with cross origins.

**Comment by dogi** [comment]
@paulbert how would I test this?

**Comment by paulbert** [comment]
@dogi Yes look at the manager view to test.  If you create a community on the "Paul" nation you will see both nation & community versions, if not you'll just see community.

**Comment by paulbert** [comment]
@dogi I'm going to merge this & we can test tomorrow.

**Pull request merged**
