### PR TITLE
Update collections & course collections (fixes #3772)

### LINKED ISSUE #3772: Course collections

### PR DESCRIPTION
**Pull request by paulbert**
@lmmrssa Haven't moved on to adding to courses so far, but have refactored for adding to resources in the new format for the `tags` database.

Remaining Todos:
- Fix the tag count (that's why the collections search is showing up as blank)
- Refactor for "Change Collections" in ResourcesComponent
- Add course collections

### CODE REVIEW

**Comment by paulbert** [comment]
Pulling the WIP label since this is a large PR already.  We can implement adding collections in the CoursesAddComponent & using the name of the collection to generate the id in another PR if this one passes testing.

To test:
- Collections for resources.  Note that any collections you have on your development environment will no longer be available.  Need to test every aspect of resource collections since there was a bit of a change to their organization
- Adding and filtering collections from the course list.  In its current state, there is no way to add collections from the course add/update page.

I think these codeclimate flags can be ignored, but if there are other issues with the PR I can fix all of it tomorrow.

**Comment by lmmrssa** [comment]
Resource add has error
Sketch (19)
Regarding Course, collection is being created on DB but not associated to course.

**Comment by svlesiv** [comment]
Overall everything works for me with some small issues:
1. Console error when saving a course if to do manipulations with collections.
Screen Shot 2019-05-13 at 7 26 24 PM
2. A collection will not be saved when creating a course for the first time.
3. When creating a course, collection selected before (previous course) will be set as default. But the course will not save that collection for the first time.

**Comment by YuserahN** [comment]
@paulbert I am unable to search resources while testing this branch. 

https://www.loom.com/share/91c6374fef584a8e9c61d49b37f05597

**Pull request merged**
