### PR TITLE
7712 challenge success message trigger mechanics (Not final ui)

### PR DESCRIPTION
**Pull request by Gavinp14**
announcmentSuccess

This is the first iteration of the success message after all steps are completed. Obviously, this needs to be changed and updated based off of the specific user reqs. Just figured I would start working on it to get an idea of where we want to go with this.

### CODE REVIEW

**Review by RheuX — APPROVED** [review]

**Review by jessewashburn — CHANGES_REQUESTED** [review]
This message will need the i18 tag, or else it won't translate. Since the audience for this course speaks Spanish, we could maybe just hardcode it too. "¡Felicidades, has completado todos los pasos!" would be the translation.

**Comment by Gavinp14** [comment]
good catch Jessie. I will make these changes once the team decides on what they want to do for the success message Ui.

**Review by sahilvunnam — COMMENTED** [review]
If PR #7721 get's approved then we would have to choose how we would format this because this PR has progress indicators that are also above the thermometer

**Comment by Gavinp14** [comment]
Exactly, I'm going to put a discussion label on this if that is the case.

**Review by jessewashburn — APPROVED** [review]

**Review by sahilvunnam — APPROVED** [review]

**Pull request merged**
