### PR TITLE
Remove Course button on cetifications-add page enabled only when course option is enabled (issue  #5820)

### LINKED ISSUE #5820: Certification: remove course should only be enabled when course option is checked
Disable Remove course if
- No course has been added
- Course is not checked.
Screenshot from 2020-02-20 20-41-05

### PR DESCRIPTION
**Pull request by sjkadali**
fixes #5820

### CODE REVIEW

**Comment by sjkadali** [comment]
@paulbert , @lmmrssa please review. Thanks!

**Comment by sjkadali** [comment]
@paulbert thanks for the review. when i set [disabled]="!courseTable?.selection?.selected?.length > 0" the Remove Courses button is disabled when the page loads and then enabled on choosing the options in the courses table. But when all the courses in the courses table are deleted,  the Remove Corses button is not disabled.

**Comment by paulbert** [comment]
`[disabled]="!courseTable?.selection?.selected?.length"` should work here.  This will disable if `length === 0` or the table is undefined.

**Comment by sjkadali** [comment]
@paulbert please review the latest commit. Thanks!

**Pull request merged**
