### PR TITLE
Change default sorting (fixes #6441)

### LINKED ISSUE #6441: Reports: Health dates sort descending
In the table by week we should sort that data oldest first by default.

### PR DESCRIPTION
**Pull request by Haoran-Hu**
fixes #6441 

Change the default sorting to descending for week dates.

### CODE REVIEW

**Comment by Haoran-Hu** [comment]
@paulbert Do not have enough data (data not longer than 2-week span)  to test the solution right now. Feedbacks would be appreciated and I can make corresponding changes.

**Comment by paulbert** [comment]
@Haoran-Hu `matSortActive` on the `mat-table` sets the initial sorting column.

Also since this table is used in a few different places, you should set this with an optional `@Input` variable (see `users-table.component.html` and `users-table.component.ts` for an example).

**Comment by Haoran-Hu** [comment]
@paulbert So the default input would be the week dates?

**Comment by Haoran-Hu** [comment]
@paulbert In `user-table.component.ts`, there isn't really a default value for the input maybe because an initial sorting column is not required. But for this issue, the initial sorting column is required.

**Comment by paulbert** [comment]
The initial sorting is required for this use of **ReportsDetailActivitiesComponent**, but other components use it that do not require sorting.

I realize you don't need to supply any new `@Input` variables.  If the `activityType` is `health`, then the `matSortActive` should be `weekOf`, otherwise it should be undefined.

**Pull request merged**
