### PR TITLE
teams: smoother list (fixes #6546)

### LINKED ISSUE #6546: Community Service: Add link dialogue box UI inconsistency
- go to Community Service
- click on Add link
- CLick on enterprise
- **Total visit from last 30 days** heading and its value is not in same line column wise
seems value is bit shifted left wards as compared to heading
Screenshot_2020-06-11 Planet Learning

### PR DESCRIPTION
**Pull request by Gavinp14**
The "Toal visits from last 30 days" column in team/enterprises and when adding links on the services tabs will be more centered and less shifted to the left. Fixes #6546

### CODE REVIEW

**Review by jessewashburn — CHANGES_REQUESTED** [review]
I'm not seeing the change. Maybe someone else can replicate? 

image

image

**Comment by Gavinp14** [comment]
@jessewashburn It works for me, I honestly could probably move it over a bit more. Have you tried replicating it on the team's page? 
totalvisistsreplication

**Review by RheuX — COMMENTED** [review]
image

If the box is small enough it will look fixed,

image

if the box is large, then it would look like jesse's

**Comment by jessewashburn** [comment]
> @RheuX I tried to make the box on my screen larger but was unable to do it. How were you able to see the "smaller" and "larger" boxes?

I think he means just resizing the screen in general, which will resize that box. As you can see, there is a sweet spot where it looks perfect but too wide or narrow a screen and the formatting breaks in general, but for that column too. 

[screen-recorder-wed-dec-04-2024-08-11-44.webm](https://github.com/user-attachments/assets/e2a35400-b662-4617-9b8f-159d3c427687)

**Comment by Gavinp14** [comment]
I was able to replicate this now, I will make changes

**Review by jessewashburn — CHANGES_REQUESTED** [review]
Unfortunately, now the most recent visit column is unaligned.

image

This seems to be one of those pages where adjusting CSS alone might not be able to give you the results you want, and the underlying structure might need some adjusting.

**Review by RheuX — COMMENTED** [review]
I got the same thing,
image

**Comment by Gavinp14** [comment]
Okay, I will see what I can do here. If I am unable to figure this out, I will put a help wanted on this issue.

**Comment by jessewashburn** [comment]
image
image

I would say it's a net improvement, but I'll defer to @Mutugiii 

Still broken on mobile, but that's probably a separate issue you may want to raise.

**Review by jessewashburn — APPROVED** [review]

**Comment by Mutugiii** [comment]
Overall agree it is a net improvement

image

**Review by Mutugiii — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
