### PR TITLE
Sort tags asc (connects #3652)

### PR DESCRIPTION
**Pull request by singharpita**

### CODE REVIEW

**Comment by singharpita** [comment]
@yuviii There is indexing script in couchdb-setup.sh that you need to run.

**Comment by yuviii** [comment]
@singharpita yeah i did it, but wondering is this the case with me only or others too. Cannot get the tags sorted still.

**Comment by lmmrssa** [comment]
@yuviii sorting seems to be working.
@singharpita Looking at picture by @yuviii it looks like sorting is case sensitive. So can you make it case insensitive.
Or @paulbert shall we make tag creation limited to lower case only? Right now we can not create same tag twice even if we change case anyway.

**Comment by yuviii** [comment]
@lmmrssa yeah u are correct. Its because of of case insensitive

**Pull request merged**
