### PR TITLE
[#916] Add a teams interface (connect #916)

### PR DESCRIPTION
**Pull request by MacNew**
screenshot-2018-5-18 planet learning
screenshot-2018-5-18 planet learning 2
screenshot-2018-5-18 planet learning

### CODE REVIEW

**Comment by lmmrssa** [comment]
This PR is completely off from issue. Issue is supposed to create team but this PR is just copying the code of users and user creation. There is no team formation.
There are empty scss files added.
As as we can see on image below. There is selection but it does nothing, also style is broken.
screen shot 2018-05-18 at 16 56 46

**Comment by MacNew** [comment]
screenshot-2018-5-21 planet learning
second

**Comment by MacNew** [comment]
screenshot-2018-5-21 planet learning
screenshot-2018-5-21 planet learning 1
screenshot-2018-5-21 planet learning 2

screen

**Comment by paulbert** [comment]
Closing this since it will just be too hard to pick out the bad changes from the things that are ok.  For example: I'm not sure why you are including adding new users from this form and I can see visual errors with the checkboxes in the table.

**Pull request closed without merging**
