### PR TITLE
Upgrade to nation version only [fix #1670, #1671, #1774]

### LINKED ISSUE #1670: software upgrade - starting with local docker tags?

### PR DESCRIPTION
**Pull request by i5o**
`http://localhost/latest` will upgrade to latest version. not available through UI
`http://localhost/upgrade?v=1.2.3` -> will upgrade to 1.2.3
`http://localhost/upgrade?v=<myTag>` will upgrade to myTag
`http://localhost/upgrade?v=latest` is the same as using `http://localhost/latest`
`http://localhost/upgrade?v=`, `http://localhost/upgrade` will return http error `400: Bad Request`

screenshot from 2018-07-27 23-29-50

### CODE REVIEW

**Comment by i5o** [comment]
to be done: show button only when `nation version > local version`
to be done: show notification of `new version available`

**Comment by i5o** [comment]
```yaml
services:
  couchdb:
    expose:
      - 5984
    image: treehouses/couchdb:2.1.2
    ports:
      - "2200:5984"
  db-init:
    image: treehouses/planet-tags:db-init-0.2.16-upgrade-to-nation-version-80725fec
    depends_on:
      - couchdb
    environment:
      - COUCHDB_HOST=http://couchdb:5984
  planet:
    image: treehouses/planet-tags:0.2.16-upgrade-to-nation-version-80725fec
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - MULTIPLE_IPS=true
      - HOST_PROTOCOL=http
      - DB_HOST=127.0.0.1
      - DB_PORT=2200
      - CENTER_ADDRESS=earth.ole.org:2200
    depends_on:
      - couchdb
version: "2"
```

**Comment by dogi** [comment]
new install method
```
wget https://raw.githubusercontent.com/open-learning-exchange/planet/<master>/docker/planet.yml
docker-compose -f planet.yml -f install.yml -p planet up -d
docker tags treehouses/planet:latest treehouses/planet:local
docker tags treehouses/planet:db-init treehouses/planet:db-init-local
docker-compose -f planet.yml -p planet up -d
```

**Comment by dogi** [comment]
autorunonce
```
#!/bin/bash

hostname='ole'
hotspotname='treehouse'

treehouses rename $hostname
treehouses expandfs
treehouses bluetooth on

# download Planet
cd /root || exit 1
wget https://raw.githubusercontent.com/open-learning-exchange/planet/upgrade-to-nation-version/docker/planet.yml
{
  echo 'services:'
  echo '  db-init:'
  echo '    image: treehouses/planet-tags:rpi-db-init-0.2.17-upgrade-to-nation-version-e0b7bbac'
  echo '  planet:'
  echo '    image: treehouses/planet-tags:rpi-0.2.17-upgrade-to-nation-version-e0b7bbac'
  echo 'version: "2"'
} > install.yml

docker-compose -f planet.yml -f install.yml -p planet pull
docker-compose -f planet.yml -f install.yml -p planet up -d
docker tag treehouses/planet-tags:rpi-db-init-0.2.17-upgrade-to-nation-version-e0b7bbac treehouses/planet:db-init-local
docker tag treehouses/planet-tags:rpi-0.2.17-upgrade-to-nation-version-e0b7bbac treehouses/planet:local
docker-compose -f planet.yml -p planet up -d


# write '/boot/autorun.sh'
{
  echo '#!/bin/sh'
  echo ''
  echo 'sleep 1'
  echo 'docker-compose -f /root/planet.yml -p planet up -d'
} > /boot/autorun

treehouses hotspot $hotspotname
```

**Comment by i5o** [comment]
autorunonce for rpi:
```
#!/bin/bash

hostname='ole'

treehouses rename $hostname
treehouses expandfs

# download Planet
cd /root || exit 1
wget https://raw.githubusercontent.com/open-learning-exchange/planet/upgrade-to-nation-version/docker/planet.yml
{
  echo 'services:'
  echo '  db-init:'
  echo '    image: treehouses/planet-tags:rpi-db-init-0.2.17-upgrade-to-nation-version-3d680a6a'
  echo '  planet:'
  echo '    image: treehouses/planet-tags:rpi-0.2.17-upgrade-to-nation-version-3d680a6a'
  echo 'version: "2"'
} > install.yml

docker-compose -f planet.yml -f install.yml -p planet pull
docker-compose -f planet.yml -f install.yml -p planet up -d
docker tag treehouses/planet-tags:rpi-db-init-0.2.17-upgrade-to-nation-version-3d680a6a treehouses/planet:db-init-local
docker tag treehouses/planet-tags:rpi-0.2.17-upgrade-to-nation-version-3d680a6a treehouses/planet:local
docker-compose -f planet.yml -p planet up -d


# write '/boot/autorun.sh'
{
  echo '#!/bin/sh'
  echo ''
  echo 'sleep 1'
  echo 'docker-compose -f /root/planet.yml -p planet up -d'
} > /boot/autorun
```

**Comment by i5o** [comment]
New commit:
```bash
#!/bin/bash

hostname='ole'

treehouses rename $hostname
treehouses expandfs

# download Planet
cd /root || exit 1
wget https://raw.githubusercontent.com/open-learning-exchange/planet/upgrade-to-nation-version/docker/planet.yml
{
  echo 'services:'
  echo '  db-init:'
  echo '    image: treehouses/planet-tags:rpi-db-init-0.2.17-upgrade-to-nation-version-c4d2c461'
  echo '  planet:'
  echo '    image: treehouses/planet-tags:rpi-0.2.17-upgrade-to-nation-version-c4d2c461'
  echo 'version: "2"'
} > install.yml

docker-compose -f planet.yml -f install.yml -p planet pull
docker-compose -f planet.yml -f install.yml -p planet up -d
docker tag treehouses/planet-tags:rpi-db-init-0.2.17-upgrade-to-nation-version-c4d2c461 treehouses/planet:db-init-local
docker tag treehouses/planet-tags:rpi-0.2.17-upgrade-to-nation-version-c4d2c461 treehouses/planet:local
docker-compose -f planet.yml -p planet up -d


# write '/boot/autorun.sh'
{
  echo '#!/bin/sh'
  echo ''
  echo 'sleep 1'
  echo 'docker-compose -f /root/planet.yml -p planet up -d'
} > /boot/autorun
```

**Comment by i5o** [comment]
When testing connect to `fosforito.media.mit.edu`. That means select the nation `fosforito`.

**Comment by lmmrssa** [comment]
tested on rpi with new script and it worked fine.
Still version does not show up correctly after upgrade due to some caching
After restart management was still showing 0.2.17
screen shot 2018-08-02 at 12 18 36
whereas main screen was showing 0.2.18
screen shot 2018-08-02 at 12 18 44

After trying to open `localhost/version` on browser and doing refresh it showed correct version on management screen as well
screen shot 2018-08-02 at 12 19 53

**Pull request merged**
