### PR TITLE
community: smoother calendar (fixes #6796)

### LINKED ISSUE #6796: Calendar: Add the space between buttons
It would be better to add a margin between the "Add Event" button and "<" and ">" buttons in a small screen size.

image

### PR DESCRIPTION
**Pull request by sahilvunnam**
fixes #6796 

@Mutugiii I believe that I fixed the calendar toolbar, are you able to check if it works for super small screens as I'm not able to check that on my laptop

### CODE REVIEW

**Review by RheuX — COMMENTED** [review]
**Here are the screenshot for your code** - I think it first started at 375 pixels
Screenshot 2024-10-31 at 7 31 36 AM

Screenshot 2024-10-31 at 7 45 43 AM

**Review by jessewashburn — CHANGES_REQUESTED** [review]
Starting around 505px width. Looks fine except when you open the toolbar, so the original issue persists. 

image

image

**Comment by sahilvunnam** [comment]
I get the same display of the buttons for Jesse - for the smallest screens I don't have the problem, but when I open the sidebar then the issue occurs for me

**Comment by sahilvunnam** [comment]
I'll try to fix the issue with the sidebar opening

**Comment by sahilvunnam** [comment]
Just fixed the issue, please check

**Comment by Gavinp14** [comment]
Do you want it to look like this with the sidebar opened or would it make more sense for all the buttons to be aligned properly?
sidebarq

**Review by RheuX — COMMENTED** [review]
image

Everthing looks good, i was just wondering if its better to have everything centered again in the calendar, since its kind of awkward if you have it in left aligned, but thats my opinion though

**Review by Gavinp14 — APPROVED** [review]

**Review by jessewashburn — CHANGES_REQUESTED** [review]
I'm still getting weird formatting when the sidebar is open on small screens. 
image

**Review by RheuX — APPROVED** [review]

**Comment by sahilvunnam** [comment]
@jessewashburn I get this for super small screens

Image 11-7-24 at 6 41 AM

**Review by jessewashburn — APPROVED** [review]

**Review by Gavinp14 — APPROVED** [review]

**Comment by Mutugiii** [comment]
Include changes from #7448 

image

image

**Review by Mutugiii — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
