### PR TITLE
Resource tags

### PR DESCRIPTION
**Pull request by paulbert**
Implementing a system for tagging/labeling resources

### CODE REVIEW

**Comment by lmmrssa** [comment]
@paulbert Is this still in progress. I couldn't test the feature. Or did i not get the clear picture of it. It is not saving tags in resources.

**Comment by i5o** [comment]
Looks good, but I would probably limit the tags to 5
image

or maybe add some "..." button after 5+ tags

**Comment by i5o** [comment]
I would also use "," as a separator for tags

**Comment by i5o** [comment]
also clicking a tag could search for it

**Comment by paulbert** [comment]
Updated with the changes that we talked about (well, we talked about making issues for...)

@lmmrssa @i5o @dogi If this still looks good we should merge so we can do more testing Thursday.

**Pull request merged**
