### PR TITLE
resources: smoother collections scrolling (fixes #6280)

### LINKED ISSUE #6280: Resources: Double horizantal scroll bar.
Go to **Resources**.
Select any resource.
Click **Change Collection**

(There is double scroll bar in the dialog if list is long like in planet.dev. This makes really hard to click on reset and ok button.)

Screenshot from 2020-05-11 09-50-56

### PR DESCRIPTION
**Pull request by Gavinp14**
fixes #6280

### CODE REVIEW

**Comment by jessewashburn** [comment]
Any advice on how to replicate? [screen-recorder-mon-dec-16-2024-14-41-11.webm](https://github.com/user-attachments/assets/33611e63-780f-4fe2-8a00-633f11be71bb)

**Comment by Gavinp14** [comment]
@jessewashburn, I did not do anything specific to replicate, it was always there. Do you have a PC or Laptop?  I'm wondering if this could only be a problem for a certain type of screen or device.

**Comment by Mutugiii** [comment]
@jessewashburn Using a higher zoom ratio should help replicate

**Comment by jessewashburn** [comment]
> @jessewashburn Using a higher zoom ratio should help replicate

Ah, I see. That did it. Only happens on Chrome btw.

**Review by jessewashburn — APPROVED** [review]

**Review by Mutugiii — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
