### PR TITLE
community challenge: popup only appears on fresh login

### PR DESCRIPTION
**Pull request by jessewashburn**
I fixed the issue where the popup happens every time the community page is refreshed. Now only happens on a new login. 

Still need to add a persistent notification.

### CODE REVIEW

**Review by Gavinp14 — APPROVED** [review]
LGTM, it only pops up on a fresh login and not every time when you refresh a page

**Comment by jessewashburn** [comment]
I am wondering if this Logout() function is called when users are logged out automatically. Also, how often are users logged out automatically? My concern would be if they are allowed to just stay logged in and thus only see the popup once and are not encouraged to do the challenge. @Mutugiii

**Comment by RheuX** [comment]
If you are concern with popup only appearing once since they have to log out and log back in, you could do either a int stored in a session storage (data would persist even on reload, only when closed they would restart, but at that point, you would have to log back in also), where every time they go to dashboard for the 3rd or 5th time it would pop up also. If not, we should implement the notification system and challenge tab for them.

**Comment by jessewashburn** [comment]
It seems when the session times out, the Login() function is not called, so I am now switching the flag upon login. 

This still leaves the issue of making it obvious to users that there's an ongoing challenge even if they have already seen the popup during that session. I will work on that tonight.

**Comment by Mutugiii** [comment]
If it is a question of permanence(assurance of not extending the session) then sessionStorage should do the trick like @RheuX has pointed out.

Though in the current implementation it seems like it would do the trick with the the removal being set on the login method

**Review by RheuX — APPROVED** [review]

**Review by Mutugiii — APPROVED** [review]

**Pull request merged**
