### PR TITLE
Use couchdb 2.2.0

### PR DESCRIPTION
**Pull request by empeje**
Depends on https://github.com/treehouses/rpi-couchdb/pull/31

Solves #2092

### CODE REVIEW

**Comment by empeje** [comment]
Please use this tag `treehouses/rpi-couchdb:2.2.0-0.0.1-v2.2.0-d81ca9b6` temporarily

**Comment by lmmrssa** [comment]
@empeje build is continuously failing

**Comment by empeje** [comment]
Yeah @lmmrssa it depends on https://github.com/treehouses/rpi-couchdb/pull/31

**Comment by empeje** [comment]
already green now @lmmrssa @paulbert

**Pull request merged**
