### PR TITLE
myplanet in fileserver

### PR DESCRIPTION
**Pull request by lmmrssa**

### CODE REVIEW

**Comment by lmmrssa** [comment]
**For RPI**
```
docker pull treehouses/planet-tags:rpi-db-init-0.7.19-2774-myplanet-b43395e0
docker pull treehouses/planet-tags:rpi-0.7.19-2774-myplanet-b43395e0
docker tag treehouses/planet-tags:rpi-db-init-0.7.19-2774-myplanet-b43395e0 treehouses/planet:db-init-local
docker tag treehouses/planet-tags:rpi-0.7.19-2774-myplanet-b43395e0 treehouses/planet:local
docker-compose -f planet.yml -p planet up -d
```

**For amd**
```
docker pull treehouses/planet-tags:db-init-0.7.19-2774-myplanet-b43395e0
docker pull treehouses/planet-tags:0.7.19-2774-myplanet-b43395e0
docker tag treehouses/planet-tags:db-init-0.7.19-2774-myplanet-b43395e0 treehouses/planet:db-init-local
docker tag treehouses/planet-tags:0.7.19-2774-myplanet-b43395e0 treehouses/planet:local
docker-compose -f planet.yml -p planet up -d
```

**Comment by paulbert** [comment]
On the raspberry pi the file is not downloaded when I bring the container up, I have to manually run `docker-entrypoint.sh`

**Comment by paulbert** [comment]
I think we can change this to run `upgrade_planetapk.sh` or `upgrade_planetapk_fromnation.sh` in the entrypoint

**Comment by lmmrssa** [comment]
Another PR has already added this feature so closing this one

**Pull request closed without merging**
