### PR TITLE
Spinner on manager-dashboard (fixes #2051)

### LINKED ISSUE #2051: loading list courses
opening the list of courses from admin-manager setting - list courses
**url in my case**
(http://localhost:3200/eng/manager/courses)
 It takes a while to load the courses list. It would be better if we show spinner to inform the course is loading.

### PR DESCRIPTION
**Pull request by BhargaviNadendla**

### CODE REVIEW

**Comment by paulbert** [comment]
@BhargaviNadendla Let me know if you have any questions or if you are no longer able to work on this.  If not, I can assign somebody else to this PR.  Thanks.

**Comment by BhargaviNadendla** [comment]
@paulbert I will fix this PR by monday, will let you know if I have any questions. Thanks

**Comment by BhargaviNadendla** [comment]
@paulbert Is this okay to add spinner on each component while the items are loading specifically or do I need to think of an alternative?

**Comment by BhargaviNadendla** [comment]
@paulbert Is this okay to add spinner on each component while the items are loading specifically or do I need to think of an alternative?

**Comment by BhargaviNadendla** [comment]
@paulbert Is this okay to add spinner on each component while the items are loading specifically or do I need to think of an alternative?

**Comment by BhargaviNadendla** [comment]
@paulbert Is this okay to add spinner on each component while the items are loading specifically or do I need to think of an alternative?

**Pull request merged**
