### PR TITLE
Added date joined to course detail (fixes #4403)

### LINKED ISSUE #4403: CourseView: Show date enrolled in course
Should we show the date a member enrolled in a course? Maybe we can put it below the description?

### PR DESCRIPTION
**Pull request by Gavinp14**
dateenrolled
fixes #4403

### CODE REVIEW

**Comment by jessewashburn** [comment]
I think you mean "Date Enrolled:"

**Review by RheuX — APPROVED** [review]

**Review by Mutugiii — COMMENTED** [review]
This seems to be the course creation date and not the specific user enrollment date

**Comment by Gavinp14** [comment]
I understand. I will have to spend some more time on this. Is there a data point in CouchDB that has a 'date enrolled' field?

**Comment by Mutugiii** [comment]
Resolved in #7840

**Pull request closed without merging**
