### PR TITLE
community: smoother calendar legend (fixes #6572)

### LINKED ISSUE #6572: Enterprises: Calendar add a legend
As of right now, it's blue for events, yellow for uncompleted tasks, and grey for completed tasks. However the only way to know that is by interacting with something within Enterprises and see what changes on the calendar.

Should we add a legend somewhere to easily show what the colors represent?

### PR DESCRIPTION
**Pull request by sahilvunnam**
fixes #6572

Image 11-13-24 at 8 37 AM

### CODE REVIEW

**Review by Gavinp14 — APPROVED** [review]

**Review by jessewashburn — APPROVED** [review]

**Review by RheuX — APPROVED** [review]

**Review by Mutugiii — CHANGES_REQUESTED** [review]
Since we only assign tasks in the teams/entreprises, it would be ideal to have 2 versions of the legend based on whether it is in community or teams/entreprises.

**Comment by RheuX** [comment]
image

image

Now both community and team/enterprise calendar is different, to add more legends, just need to add more element and give a type

**Review by Mutugiii — APPROVED** [review]

**Review by jessewashburn — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Review by dogi — CHANGES_REQUESTED** [review]
move these legend to the buttom
maybe also rethink about what and how to show
is "event legend" title necessary

**Comment by RheuX** [comment]
Now I change it to the bottom right, it looks cleaner

image

image


if the screen is small, it should wrap also.

**Review by Mutugiii — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
