### PR TITLE
Achievements: add icons and isClickable check (fixes #3251)

### LINKED ISSUE #3251: Achievements: Show description/attachments icon
On our new achievement view, we have achievement collapsable. So we do not see attachment until we click on each achievement.
screen shot 2019-02-21 at 13 30 02
screen shot 2019-02-21 at 13 30 09

### PR DESCRIPTION
**Pull request by svlesiv**
screen shot 2019-02-22 at 1 26 12 pm

### CODE REVIEW

**Comment by yuviii** [comment]
@singharpita  agreed. @svlesiv I think it is better to show cursor when hovered through the icon either it is both or one between description and resources.

**Comment by svlesiv** [comment]
@singharpita and @yuviii, thank you for noticing this bug. I've fixed it. Now it should work properly.

**Comment by svlesiv** [comment]
Hi @lmmrssa, thanks for the review. I will try to fix it.

**Comment by svlesiv** [comment]
screen shot 2019-02-25 at 11 49 30 am

**Comment by svlesiv** [comment]
Or it can be different icons:

screen shot 2019-02-25 at 12 12 48 pm

**Comment by paulbert** [comment]
@svlesiv I think having the icon to the right of the title would be preferable so all of the titles line up & the title is the first thing you read.  Leaning towards the chevron arrow, also.

**Comment by svlesiv** [comment]
Sure, I will fix it.

**Pull request merged**
