### PR TITLE
Enterprise Reports: Validate number fields

### LINKED ISSUE #6910: Enterprise Reports: Income & Expenses only positive numbers allowed
Do not allow negative value
Lets make it same as financial transaction

### PR DESCRIPTION
**Pull request by jsschf**
Fixes #6910

### CODE REVIEW

**Comment by jsschf** [comment]
@paulbert I'm in **TeamsReportsComponent** and I'm confused on how to validate the fields as there isn't a Form Control. I see the fields in `openAddReportDialog()`, but I can't find any relevant input fields. 

Any guidance would be appreciated.

**Comment by paulbert** [comment]
@jsschf In `addFormInitialValues` there is a `formControl` function.  This creates arrays for setting the **FormControl** values with **FormBuilder.group**.

I used that function since all of the fields are required and it cut down on some repetition to set things that way.  We already have one additional validator for `endDate`, but you could add another to that array if the field name matches any of the four in the issue.

https://angular.io/api/forms/FormBuilder#group

**Comment by jsschf** [comment]
@paulbert Ok thanks that makes more sense

**Comment by jsschf** [comment]
This should also make it easier to add the endDate validation for this issue #6912

**Pull request merged**
