### PR TITLE
[#1647] Added retry option when the docker timeouts (fixes #1647)

### LINKED ISSUE #1647: software upgrade - fix message when timeout
screenshot_20180712_120345

### PR DESCRIPTION
**Pull request by i5o**
screenshot from 2018-07-13 20-28-56
screenshot from 2018-07-13 20-29-18

we can change the colors

### CODE REVIEW

**Comment by dogi** [comment]
awesome @i5o

**Comment by lmmrssa** [comment]
@i5o can we have some number of limit to retries and if it does not pass then show Failed message. Otherwise it will keep retrying continuously.

**Comment by i5o** [comment]
Sure @lmmrssa. I guess we can add 5, after that we ask the user to submit feedback.
When the page is reloaded that "5" will be lost, is that ok?

**Comment by lmmrssa** [comment]
@i5o yes it is ok As after reload user will have to again click button to trigger it. We just need to be able to notify user

**Comment by i5o** [comment]
image

**Pull request merged**
