### PR TITLE
2805 leave count on course with no step

### PR DESCRIPTION
**Pull request by BhargaviNadendla**

### CODE REVIEW

**Comment by lmmrssa** [comment]
@BhargaviNadendla can you commit this fixes under https://github.com/open-learning-exchange/planet/issues/2824

**Comment by BhargaviNadendla** [comment]
> @BhargaviNadendla can you commit this fixes under #2824

Sure!

**Comment by BhargaviNadendla** [comment]
@lmmrssa Sure! I just created a new pull request

**Comment by paulbert** [comment]
Closing in favor of #2835

**Pull request closed without merging**
